### ISSUE TITLE
Incorrect differences_detected in zpa_server_group.py for newly added app connector groups

### ISSUE THREAD

**Issue by CKroes97** [zscaler/zpacloud-ansible#48]
## Describe the bug

When updating the app connector groups on a server group, the zpa_server_group.py module sometimes incorrectly does not detect differences. I suspect that the current logic for differences detected does not work properly with lists.

## Expected behavior

  - name: Add new app connector group in server groups paralel to appcon group that needs to be replaced
    zscaler.zpacloud.zpa_server_group:
      provider: "{{ zpa_cloud }}"
      id: "{{ item['id'] }}"
      name: "{{ item['name'] }}"
      app_connector_group_ids: "{{ (item['app_connector_group_ids'] + [new_connector_group_id]) | list  }}" 
    loop: "{{ server_groups }}"

The playbook above should add the new_connector_group_id to each server group. In about half of our server groups, this leads to an "OK" without changes. When running with check_mode, we also get an "OK" without changes. When adding a space after the name to trigger the differences to be detected, the code works as expected, including the addition of the app connector groups

Working code:

  - name: Add new app connector group in server groups paralel to appcon group that needs to be replaced
    zscaler.zpacloud.zpa_server_group:
      provider: "{{ zpa_cloud }}"
      id: "{{ item['id'] }}"
      name: "{{ item['name'] + ' ' }}"
      app_connector_group_ids: "{{ (item['app_connector_group_ids'] + [new_connector_group_id]) | list  }}" 
    loop: "{{ server_groups }}"

## Current behavior

The changes to the app connector group ids are not properly detected and no changes are made.

## Possible solution

Review the logic for setting "differences_dtected = true. I suspect it is either  the case that the comparison logic does not work properly for lists, or perhaps the "Fields_to_exclude" trip things up, although I find the earlier hypothesis more logical.

## Steps to reproduce
Add a new app connector group to a batch of server groups, some of them will seemingly randomly fail:

  - name: Add new app connector group in server groups paralel to appcon group that needs to be replaced
    zscaler.zpacloud.zpa_server_group:
      provider: "{{ zpa_cloud }}"
      id: "{{ item['id'] }}"
      name: "{{ item['name'] }}"
      app_connector_group_ids: "{{ (item['app_connector_group_ids'] + [new_connector_group_id]) | list  }}" 
    loop: "{{ server_groups }}"

## Context

We want to add a newly created app connector group to server groups

## Your Environment

Collection: zscaler.zpacloud:1.4
Python: 3.9.19
Ansible: 9.4 (not entirely sure)
Zscaler SDK Python Library & version: zscaler-sdk-python 0.9.4

**Comment by willguibr** [comment]
@CKroes97 
We have responded via the support case which was raised with our team 4 days ago but to expedite the update here is the analysis.
**Original Playbook Behavior:**

Initially, the playbook was using this line to modify the app_connector_group_ids:
```sh
app_connector_group_ids: "{{ item['app_connector_group_ids'] + [connector_grp_id] }}"
```
This line appended the new connector_grp_id to the existing list of app_connector_group_ids but did not replace the old one. As a result, instead of replacing the existing ID with the new one, it simply added the new ID to the list alongside the old one. Here's why this happened:

**1.  Appending Instead of Replacing:** In Python (and Jinja2), the + operator on lists concatenates them. So, item['app_connector_group_ids'] + [connector_grp_id] was combining the current list of connector IDs with the new ID without removing the old one.

If app_connector_group_ids initially contained ['216199618143482156'], after running this statement, it would contain ['216199618143482156', '216199618143482159']—both the old and new IDs.
2. Why It Was Skipped Initially: The original when condition checked if:

```sh
when: (replaced_grp_id in item['app_connector_group_ids']) and (connector_grp_id not in item['app_connector_group_ids'])
```

This condition was false because the connector_grp_id was not part of app_connector_group_ids. The task was skipped because the second part of the condition, (connector_grp_id not in item['app_connector_group_ids']), was true, but the task wasn’t designed to remove the old ID. So, no replacement logic was in place.

**Original Playbook Behavior:**

**1. No Mechanism to Remove the Old ID:** The original playbook did not account for removing the replaced_grp_id from the list of app_connector_group_ids. It only added the new connector_grp_id, which is why the old ID persisted.

**2. Logical Misalignment in the when Condition:** The when condition was designed to ensure the update only occurred if the replaced_grp_id was in the list and the connector_grp_id was not. However, it didn't handle the scenario of replacing the existing connector group ID. The assumption was that the new ID would just be added, which wasn't what you intended.

**Solution:**

The correct approach involved using the difference filter in Jinja2 to remove the replaced_grp_id from the list before appending the connector_grp_id. Here's the breakdown of what the solution does:

**1. Removing the Old ID:** The difference filter was used to remove the replaced_grp_id from the list:
```sh
app_connector_group_ids: "{{ (item['app_connector_group_ids'] | difference([replaced_grp_id])) + [connector_grp_id] }}"
```

item['app_connector_group_ids'] | difference([replaced_grp_id]): This line filters out the replaced_grp_id from the list.
The resulting list is then combined with the [connector_grp_id] to include the new connector group ID.

**2. Replacing Instead of Adding:** The combination of filtering out the old ID and adding the new ID ensures that the new list of app_connector_group_ids contains only the new connector group ID (connector_grp_id), effectively replacing the old one (replaced_grp_id).

**Summary of the Problem:**

**Original Behavior:** The playbook appended the new connector group ID (connector_grp_id) without removing the old one (replaced_grp_id), leading to both IDs being present in the list.
Root Cause: The absence of logic to remove the old replaced_grp_id before appending the new one.

**Solution:** Use the difference filter to remove the old ID, and then append the new one, ensuring the old connector group ID is replaced with the new one.
Please see attached the corrected playbook(s) example.
[Archive.zip](https://github.com/user-attachments/files/17546466/Archive.zip)

**Comment by CKroes97** [comment]
Hi @willguibr,


Thanks for having a look at this issue!

My issue is neither with the the old app connector group remaining, which is by design (the removal is done in another playbook to give us more control). The issue is also not with the evaluation of the "when" statement which works as designed, the task runs when it needs to and does not run when it should not. 

We do have an issue with unexpected "ok" results when adding the new group next to the old group, with as a result no changes being made in the ZPA portal. When running in check_mode the result is also "ok" instead of "changed". When adding the new group it sometimes results in "changed" and sometimes in "ok". The issues is always the same for the same server group though, so a server group will always either result in "changed" when a new group is added, or in "ok".

Changing the name statement to:
name: "{{ item['name'] + ' ' }}"

This causes both the result to be changed but **more importantly**: it makes sure the app connector group is actually added to the server group in ZPA, which does not happen otherwise. I do still strongly feel like there is an issue in the module logic because of the reason that this workaround works and solves our issue. I can submit more supporting logs but then via the support case due to the sensitivity of the case.

**Comment by CKroes97** [comment]
Just a hunch, I see that before the check_differences is ran, we have the following code:

````
desired_app = normalize_app(server_group)
current_app = normalize_app(existing_server_group) if existing_server_group else {}
```

   
   
   looking at the module_utils/utils.py, there is this code:
   
```
   def normalize_app(app):
    normalized = app.copy()
    computed_values = [
        "creation_time",
        "modified_by",
        "modified_time",
        "id",
        "config_space",
        "microtenant_name",
        "segment_group_name",
        "server_groups",
        "use_in_dr_mode",
        "is_incomplete_dr_config",
        "inspect_traffic_with_zia",
        "adp_enabled",
        "app_id",
        "ip_anchored",
        "action",
        "control_number",
        "control_rule_json",
        "protocol_type",
        "rules",
        "version",
        "threatlabz_controls",
        "websocket_controls",
        "zs_defined_control_choice",
        "predef_controls_version",
        "incarnation_number",
        "control_type",
        "check_control_deployment_status",
        "controls_facts",
        "lss_app_connector_group",
        "app_connector_group_ids",
        "clientless_app_ids",
    ]
    for attr in computed_values:
        normalized.pop(attr, None)
        
```
        
Then some more code and finally

`return normalized`
        
If I understand this correctly, the app_connector_group_ids are removed from the app connector before making the comparison, meaning that the app_connector_group_ids are excluded from the comparisson. Could this be right?

**Comment by willguibr** [comment]
@CKroes97 
Please contact me offline via wguilherme@<you_know_the_rest>
